### ISSUE TITLE
[iOS] FAQ

### ISSUE THREAD

**Issue by nizmaylova** [openedx/openedx-app-ios#119]
Need to add FAQ

![Image](https://github.com/openedx/openedx-app-ios/assets/121940663/4d8681da-776b-49fd-8891-b20a104fa77e)

**Comment by moiz994** [comment]
Acceptance Criteria:
- Tapping the FAQ button should redirect the user to the mobile browser to a specified webpage 
- Webpage is URL is configurable and maintained in the app config 
- This should be implemented behind a feature flag

**Comment by rnr** [comment]
@moiz994 
"Tapping the FAQ button should redirect the user to the mobile browser to a specified webpage"
do you mean here in the app webpage or external mobile browser (Safari app)?
thank you

**Comment by moiz994** [comment]
@rnr the external mobile browser.

**Comment by rnr** [comment]
@moiz994 Do we get any benefits from using an external browser instead of a webView in the application? Thank you

**Comment by moiz994** [comment]
@rnr good question, right now this is the legacy functionality that we're targeting to be in parity with before launch. There isn't any special benefit other than that this page is not optimized for webview currently so we direct the user to the mobile browser.

**Comment by rnr** [comment]
<img width="1017" alt="Screenshot 2023-12-13 at 18 58 58" src="https://github.com/openedx/openedx-app-ios/assets/37253/5f56b829-a654-4041-8876-d2ddb6b01490">
@moiz994 The page is not optimized for viewing in the web version of the app or for mobile Safari. 
If no difference then do you think we still need to redirect outside?
cc @touchapp @marcotuts

**Comment by moiz994** [comment]
@rnr thanks for sharing these screenshots. As you can see this page has a header where it shows the breadcrumbs, if this URL is implemented as a webview in the app, the users can start exploring almost the whole edX website within the app. The web team usually removes headers and footers for us and provides a URL for webviews for the app. Since we don't have one for this page ready, we need to direct the user to the browser for this page. 
Maybe after the MVP we can look at bringing this in as native content but for now, let's focus on parity. 

cc: @miankhalid
