### ISSUE TITLE
[iOS] Loading indicator displays for a long time for content with  "webview"

### ISSUE THREAD

**Issue by sergeymomot** [openedx/openedx-app-ios#221]
https://learning.stage.edx.org/course/course-v1:ArbiSoftDemo+CS111+2017_LT/block-v1:ArbiSoftDemo+CS111+2017_LT+type@sequential+block@458aaf85354f4fc6b781a5d55fac2fb3/block-v1:ArbiSoftDemo+CS111+2017_LT+type@vertical+block@741e625741dd42668b213eae40dc652a

For content with "webview" a loading indicator is shown, which is displayed for about two minutes; this is repeated every time this content (card) is opened. 

<img width="280" alt="39441036-d0e1-44cd-8aba-3118f87c81bd" src="https://github.com/openedx/openedx-app-ios/assets/2964930/39441036-d0e1-44cd-8aba-3118f87c81bd">

https://github.com/openedx/openedx-app-ios/assets/2964930/95a5f834-22b5-40d3-b682-04ee91d28619

**Comment by forgotvas** [comment]
@miankhalid It happens because that content has sync loading for script with src `https://ads.avocet.io/s?add=5874b623fa52da123477a5da&tv=i` that cause timeout. I can reproduce that only on staging environment. Should we find workaround that problem or that is not usual thing for production environment.

**Comment by rnr** [comment]
close as Staging env related only
